export default {
  reporter: {
    type: 'html',
  },
  featureDirectory: './tests/acceptance/features',
  rules: {
    indentation: [
      'warn',
      {
        feature: 3,
        background: 3,
        scenario: 3,
        step: 5,
        examples: 5,
        given: 1,
        when: 5,
        then: 1,
        and: 5,
        but: 5,
        exampleTableHeader: 7,
        exampleTableBody: 7,
        scenarioOutline: 3,
      },
    ],
    'new-line-at-eof': 'warn',
    'no-background-only': 'warn',
    'no-empty-file': 'warn',
    'no-trailing-spaces': 'warn',
    'no-unnamed-scenarios': 'warn',
    'aligned-datatables': 'error',
    'filename-snake-case': 'error',
    'disallowed-tags': ['@development'],
    'feature-description': 'error',
  },
}
