name: Gherklin

on:
  workflow_call:
    inputs:
      nodeVersions:
        required: true
        type: string
      osVersions:
        required: true
        type: string

jobs:
  run-gherklin:
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.define-matrix.outputs.nodeVersions) }}
        os: ${{ fromJSON(needs.define-matrix.outputs.osVersions) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Run Gherklin
      run: npm run gherklin
